# Generated by Django 4.1.6 on 2023-02-13 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("des", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 14, 2, 20, 5, 967382)
                    ),
                ),
            ],
        ),
    ]
